<h1>Welcome To Our Training</h1>

<?php /** @var \Magento\Framework\View\Element\Template $block */

echo 'Your XYZ is '. ($block->getData('isEnabled') ? 'enabled' : 'disabled');

/** @var \SwiftOtter\Training\ViewModel\ViewModel $viewModel */
$viewModel = $block->getData('viewModel');

echo '<h1>'.$viewModel->getCustomString().'</h1>';

// Loop of Products

echo '<div style="border: 1px #00F; padding:25px;"><ol>';
/** @var \Magento\Catalog\Api\Data\ProductInterface $product */
foreach ($viewModel->getProducts() as $product) {
    echo '<li>'.$product->getName().' costs: '.$product->getPrice().'</li>';
}
echo '</ol></div>';

// After plugin

echo '<ul>';
foreach ($viewModel->getListOfEUCountries() as $euCountry) {
    echo '<li>'.$euCountry.'</li>';
}
echo '</ul>';

// Around plugin

echo '<div style="border: 1px solid #f00; padding: 10px;">'.$viewModel->getLazyMethod().'</div>';
echo '<div style="border: 1px solid #f00; padding: 10px;">'.$viewModel->getLazyMethod().'</div>';
echo '<div style="border: 1px solid #f00; padding: 10px;">'.$viewModel->getLazyMethod().'</div>';
echo '<div style="border: 1px solid #f00; padding: 10px;">'.$viewModel->getLazyMethod().'</div>';
echo '<div style="border: 1px solid #f00; padding: 10px;">'.$viewModel->getLazyMethod().'</div>';

// Before Plugin

echo '<ol>';
foreach ($viewModel->getPriceList(['soap', 'bread', 'whatever']) as $sku => $price) {
    echo '<li><strong>SKU: '.$sku.'</strong> costs you '.$price.'</li>';
}
echo '</ol>';

echo '<hr/>';

echo '<h1>'.$viewModel->isAddressValid().'</h1>';
